"""add review log idempotency key

Revision ID: b3c4eb4d311f
Revises: e6a91c832393
Create Date: 2026-08-21 11:12:57.653763

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b3c4eb4d311f'
down_revision: str | None = 'e6a91c832393'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review_logs', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.create_index('uq_review_logs_user_idempotency_key', 'review_logs', ['user_id', 'idempotency_key'], unique=True, postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_review_logs_user_idempotency_key', table_name='review_logs', postgresql_where=sa.text('idempotency_key IS NOT NULL'))
    op.drop_column('review_logs', 'idempotency_key')
    # ### end Alembic commands ###
