"""add note types, notes, cards, media, import jobs

Revision ID: d72026aab27e
Revises: 704ea35be18a
Create Date: 2026-08-21 00:58:41.076028

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd72026aab27e'
down_revision: str | None = '704ea35be18a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('progress', sa.SmallInteger(), nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_detail', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('media_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('sha256', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'filename', name='uq_media_files_user_filename')
    )
    op.create_table('note_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('kind', sa.SmallInteger(), nullable=False),
    sa.Column('css', sa.Text(), nullable=False),
    sa.Column('latex_pre', sa.Text(), nullable=False),
    sa.Column('latex_post', sa.Text(), nullable=False),
    sa.Column('sort_field_ord', sa.Integer(), nullable=False),
    sa.Column('anki_notetype_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_type_id', sa.UUID(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('question_format', sa.Text(), nullable=False),
    sa.Column('answer_format', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['note_type_id'], ['note_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_type_id', 'ord', name='uq_card_templates_ord')
    )
    op.create_table('note_type_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('note_type_id', sa.UUID(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_rtl', sa.Boolean(), nullable=False),
    sa.Column('font', sa.String(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['note_type_id'], ['note_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_type_id', 'ord', name='uq_note_type_fields_ord')
    )
    op.create_table('notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('note_type_id', sa.UUID(), nullable=False),
    sa.Column('guid', sa.String(), nullable=False),
    sa.Column('fields', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('checksum', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_type_id'], ['note_types.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'guid', name='uq_notes_user_guid')
    )
    op.create_index('notes_guid_idx', 'notes', ['user_id', 'guid'], unique=False)
    op.create_table('cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('note_id', sa.UUID(), nullable=False),
    sa.Column('deck_id', sa.UUID(), nullable=False),
    sa.Column('template_ord', sa.Integer(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('queue', sa.SmallInteger(), nullable=False),
    sa.Column('due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('new_position', sa.Integer(), nullable=True),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('elapsed_days', sa.Integer(), nullable=False),
    sa.Column('scheduled_days', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('lapses', sa.Integer(), nullable=False),
    sa.Column('learning_step', sa.Integer(), nullable=False),
    sa.Column('last_review', sa.DateTime(timezone=True), nullable=True),
    sa.Column('anki_card_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', 'template_ord', name='uq_cards_note_template_ord')
    )
    op.create_index('cards_due_idx', 'cards', ['user_id', 'deck_id', 'queue', 'state', 'due'], unique=False, postgresql_where=sa.text('queue = 0'))
    op.create_index('cards_new_idx', 'cards', ['user_id', 'deck_id', 'new_position'], unique=False, postgresql_where=sa.text('queue = 0 AND state = 0'))
    op.create_table('review_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('card_id', sa.UUID(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('state_before', sa.SmallInteger(), nullable=False),
    sa.Column('scheduled_days', sa.Integer(), nullable=False),
    sa.Column('elapsed_days', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('imported', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_logs')
    op.drop_index('cards_new_idx', table_name='cards', postgresql_where=sa.text('queue = 0 AND state = 0'))
    op.drop_index('cards_due_idx', table_name='cards', postgresql_where=sa.text('queue = 0'))
    op.drop_table('cards')
    op.drop_index('notes_guid_idx', table_name='notes')
    op.drop_table('notes')
    op.drop_table('note_type_fields')
    op.drop_table('card_templates')
    op.drop_table('note_types')
    op.drop_table('media_files')
    op.drop_table('import_jobs')
    # ### end Alembic commands ###
