"""add card bury tracking and review log undo snapshot

Revision ID: e6a91c832393
Revises: d72026aab27e
Create Date: 2026-08-21 11:05:23.592638

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e6a91c832393'
down_revision: str | None = 'd72026aab27e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('buried_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('review_logs', sa.Column('previous_state', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review_logs', 'previous_state')
    op.drop_column('cards', 'buried_at')
    # ### end Alembic commands ###
